/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-05 16:09:48 UTC)
 * on 2013-06-17 at 08:15:10 UTC 
 * Modify at your own risk.
 */

package com.crashdev.buyauser.ofertaendpoint.model;

/**
 * Model definition for Oferta.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Oferta extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String advertaicer;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String condiciones;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String descripcion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String imagen;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String titulo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String vigencia;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAdvertaicer() {
    return advertaicer;
  }

  /**
   * @param advertaicer advertaicer or {@code null} for none
   */
  public Oferta setAdvertaicer(java.lang.String advertaicer) {
    this.advertaicer = advertaicer;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCondiciones() {
    return condiciones;
  }

  /**
   * @param condiciones condiciones or {@code null} for none
   */
  public Oferta setCondiciones(java.lang.String condiciones) {
    this.condiciones = condiciones;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescripcion() {
    return descripcion;
  }

  /**
   * @param descripcion descripcion or {@code null} for none
   */
  public Oferta setDescripcion(java.lang.String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Oferta setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getImagen() {
    return imagen;
  }

  /**
   * @param imagen imagen or {@code null} for none
   */
  public Oferta setImagen(java.lang.String imagen) {
    this.imagen = imagen;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitulo() {
    return titulo;
  }

  /**
   * @param titulo titulo or {@code null} for none
   */
  public Oferta setTitulo(java.lang.String titulo) {
    this.titulo = titulo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getVigencia() {
    return vigencia;
  }

  /**
   * @param vigencia vigencia or {@code null} for none
   */
  public Oferta setVigencia(java.lang.String vigencia) {
    this.vigencia = vigencia;
    return this;
  }

  @Override
  public Oferta set(String fieldName, Object value) {
    return (Oferta) super.set(fieldName, value);
  }

  @Override
  public Oferta clone() {
    return (Oferta) super.clone();
  }

}
